categories: [Sequence Analysis]
description: Automatically identify makers predictive of groups.
name: feht
owner: nml
long_description: A commandline program to automatically identify markers predictive of groups. Can be used with binary data, genomic (single nucleotide variant) data, or arbitrary character data.
remote_repository_url: https://github.com/phac-nml/galaxy_tools
homepage_url: https://github.com/phac-nml/galaxy_tools
