categories: [Sequence Analysis]
description: RScript to parse the results of mykrobe predictor.
name: mykrobe_parseR
owner: nml
long_description: mykrobe_parseR - RScript to parse the results of mykrobe predictor and present them in a LIMS compatible format (.csv)
remote_repository_url: https://gitlab.cscscience.ca/AZetner/mykrobe-parser
homepage_url: https://gitlab.cscscience.ca/AZetner/mykrobe-parser
