categories: [Supplementary]
description: Convert BioHansel output data to a Bionumerics friendly form
name: biohansel_bionumeric_converter 
owner: nml
homepage_url: https://github.com/phac-nml/galaxy_tools